[project]
name = "momask-codes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "einops>=0.8.1",
    "flax>=0.10.7",
    "torch>=2.9.1",
]
